### PR TITLE
Parse error messages for Flutter reports

### LINKED ISSUE #30: Parse error messages for Flutter reports
Right now `RawDetails` of the annotation is empty. We can parse it from entries like:

```json
{"testID":4,"error":"Expected: <0>\n  Actual: <1>\n","stackTrace":"package:test_api            expect\ntest/counter_test.dart 7:7  main.<fn>.<fn>\n","isFailure":true,"type":"error","time":3350}
```

### PR DESCRIPTION
**Pull request by edigaryev**
Resolves #30.

### CODE REVIEW

File: parsers/flutter.go [hunk 1]
```diff
@@ -18,13 +18,14 @@ type flutterTest struct {
...
 	Result string
 	Test   flutterTest
 }
 
-func annotationFromTest(test flutterTest) model.Annotation {
-	return model.Annotation{
+func annotationFromTest(test *flutterTest) *model.Annotation {
+	return &model.Annotation{
 		Type:    model.TestResultAnnotationType,
 		Level:   "failure",
```
Comment (fkorotkov) [inline parsers/flutter.go:30]: Let's not set level here then (since it's created on a test start). And instead set the level on testDone before appending the annotation.

Comment (edigaryev) [reply parsers/flutter.go]: See https://github.com/cirruslabs/cirrus-ci-annotations/pull/31/commits/cf5507b6d061aa6ba9665d300d896825882ce00d.

**Review by fkorotkov — APPROVED** [review]
